services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: ommrgazar315/ai:1.0
    container_name: ai
    ports:
      - "8005:8000"
    environment:
      - API_BASE_URL=https://furnisique.servehttp.com/api
      - LOG_LEVEL=info
    volumes:
      - ai:/app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/api/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s