services:
  recommendation:
    build:
      context: .
      dockerfile: Dockerfile
    image: ommrgazar315/recommendation:1.0
    container_name: recommendation
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=https://furnisique.servehttp.com/api
      - LOG_LEVEL=info
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/api/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  recommendation-service-data:
    driver: local
    driver_opts:
      type: none
      device: /var/www/recommendation
      o: bind