# Unique Component Names
MOBILE_APP = "Mobile App (Flutter)"
WEB_INTERFACE = "Web Interface"
BACKEND = "Backend (Laravel)"
DATABASE = "Database (MySQL)"
AI_ENGINE = "AI Recommendation Engine"
PAYMENT_GATEWAY = "Payment Gateway"
ORDER_MANAGEMENT = "Order Management System"
INVENTORY_MANAGEMENT = "Inventory Management System"
SHIPPING_API = "Shipping & Logistics API"
SUPPLIER_API = "Supplier API"

# User Roles
CUSTOMER = "Customer"
ADMIN = "Admin"

# Features
PRODUCT_SEARCH = "Product Search"
FURNITURE_RECOMMENDATION = "Furniture Recommendation"
ORDER_PLACEMENT = "Order Placement"
PAYMENT_PROCESSING = "Payment Processing"
ORDER_TRACKING = "Order Tracking"
CUSTOMER_SUPPORT = "Customer Support"
SUPPLIER_MANAGEMENT = "Supplier Management"

# Communication Diagram Constants
COMMUNICATION_NODES = [
    MOBILE_APP, WEB_INTERFACE, BACKEND, DATABASE, AI_ENGINE,
    PAYMENT_GATEWAY, ORDER_MANAGEMENT, INVENTORY_MANAGEMENT,
    SHIPPING_API, SUPPLIER_API
]

COMMUNICATION_EDGES = [
    (MOBILE_APP, BACKEND),
    (WEB_INTERFACE, BACKEND),
    (BACKEND, DATABASE),
    (BACKEND, AI_ENGINE),
    (BACKEND, PAYMENT_GATEWAY),
    (BACKEND, ORDER_MANAGEMENT),
    (ORDER_MANAGEMENT, INVENTORY_MANAGEMENT),
    (ORDER_MANAGEMENT, SHIPPING_API),
    (INVENTORY_MANAGEMENT, SUPPLIER_API)
]

# Interaction Matrix Components & Data
INTERACTION_COMPONENTS = [
    MOBILE_APP, WEB_INTERFACE, BACKEND, DATABASE, AI_ENGINE, PAYMENT_GATEWAY,
    ORDER_MANAGEMENT, INVENTORY_MANAGEMENT, SHIPPING_API, SUPPLIER_API
]

INTERACTION_MATRIX = [
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
]

# Usage Diagram Constants
USAGE_NODES = [
    CUSTOMER, ADMIN, MOBILE_APP, WEB_INTERFACE, PRODUCT_SEARCH,
    FURNITURE_RECOMMENDATION, ORDER_PLACEMENT, PAYMENT_PROCESSING,
    ORDER_TRACKING, CUSTOMER_SUPPORT, INVENTORY_MANAGEMENT, SUPPLIER_MANAGEMENT
]

USAGE_EDGES = [
    (CUSTOMER, MOBILE_APP),
    (CUSTOMER, WEB_INTERFACE),
    (MOBILE_APP, PRODUCT_SEARCH),
    (WEB_INTERFACE, PRODUCT_SEARCH),
    (PRODUCT_SEARCH, FURNITURE_RECOMMENDATION),
    (FURNITURE_RECOMMENDATION, ORDER_PLACEMENT),
    (ORDER_PLACEMENT, PAYMENT_PROCESSING),
    (ORDER_PLACEMENT, ORDER_TRACKING),
    (CUSTOMER, CUSTOMER_SUPPORT),
    (ADMIN, INVENTORY_MANAGEMENT),
    (ADMIN, SUPPLIER_MANAGEMENT)
]

# User Location Diagram Constants
CUSTOMER_MOBILE = "Customer (Mobile App)"
CUSTOMER_WEB = "Customer (Web Interface)"
ADMIN_PANEL = "Admin (Web Panel)"

LOCATION_NODES = [
    CUSTOMER_MOBILE, CUSTOMER_WEB, ADMIN_PANEL,
    BACKEND, DATABASE, AI_ENGINE, SUPPLIER_API, SHIPPING_API, PAYMENT_GATEWAY
]

LOCATION_EDGES = [
    (CUSTOMER_MOBILE, BACKEND),
    (CUSTOMER_WEB, BACKEND),
    (ADMIN_PANEL, BACKEND),
    (BACKEND, DATABASE),
    (BACKEND, AI_ENGINE),
    (BACKEND, PAYMENT_GATEWAY),
    (BACKEND, SUPPLIER_API),
    (BACKEND, SHIPPING_API)
]
